education_project/urls.py
import notifications
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView, RedirectView
from admin_api import views as vw

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("student.urls")),
    path('', include('django.contrib.auth.urls')),
    path('', include('rest_framework.urls')), # will add login button at the top right corner :)
    path('user_all/', vw.index, name='all'),
    path('create_user/', vw.create_user, name='create_user'),
    path('update_user/<int:id>', vw.update_user, name='update_user'),
    path('course_all/', vw.index_course, name='all'),
    path('create_course/', vw.create_course, name='create_user'),
    path('update_course/<int:id>', vw.update_course, name='update_user'),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
import notifications.urls
from django.conf.urls import url
from django.urls import path, include
from . import views
from admin_api import views as vw
from .views import *


app_name = "student"
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('team/', views.team, name='team'),
    path('students/', views.courses, name='courses'),
    path("register/", views.registerView, name="registration"),
    path("user/<username>", ProfileView.as_view(), name="profile"),
    path("login/", views.login_request, name="login"),
    path("admin_panel/", views.admin, name="admin"),
    path('team/python', views.python, name='python'),
    path('team/python_lesson1', views.pythonlesson1, name='python1'),
    path('team/python_lesson2', views.pythonlesson2, name='python2'),
    path('team/cpp', views.cpp, name='cpp'),
    path('team/cpp_lesson1', views.cpplesson1, name='cpp1'),
    path('teacher/', views.teacher, name='teacher'),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        Main page
    </title>
    {% load static %}
    <link rel="stylesheet"  href="{%  static  'css/main.css'  %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" charset="utf-8"></script>
    <script src="https://kit.fontawesome.com/80480a3d8b.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
</head>

<body>
    <header>
			<a href="index.html" ><img src="img\headlogo.png" alt="" class="logoh"></a>

	        <!--Navigation bar-->
	        <nav>
	        	<ul class="navigation">
		         	<li><a href="index.html"><i class="fas fa-home home"></i> Home</a></li>
		       	 	<li><a href="about.html" class="active_link"><i class="fas fa-align-left about"></i> About</a></li>
		       	 	<li><a href="gallery.html"><i class="fas fa-camera gallery"></i> Gallery</a></li>
		            <li><a href="team.html"><i class="fas fa-users team"></i> Team</a></li>
		            <li><a href="login.html"><i class="fas fa-sign-in-alt login"></i> Login</a></li>
	            </ul>
	        </nav>
 			<!--Logo of menu which will show up when the screen is reduced-->
	        <i class="menu fas fa-bars"></i>
	        <div class="progress-container">
    			<div class="progress-bar" id="myBar"></div>
  			</div>
		</header>

		<main>
			<div class="about-content shadowed">

				<div class="tabs">

					<div class="tabs-header">
						<div class="tab-h active-border" data-tab = "0">Today</div>
						<div class="tab-h" data-tab = "1">History</div>
						<div class="tab-h" data-tab = "2">Values</div>
					</div>
					<div class="tabs-body">
						<div class="tab-b" style="display: block;"> </div>
						<div class="tab-b"> The restaurants were created after the popular k-pop group "BLackpink". All the inspiration was taken from them. The very first restaurant was opened on 9th of August in 2016, after a day when the group debuted.</div>
						<div class="tab-b">
							<ol>
								<li>It has to be made with love.</li>
								<li>Quality of the food.</li>
								<li>The food should be not only tasty, but it has to look tasty.</li>
								<li>The food should be served on a high level.</li>
							</ol>
						</div>
					</div>

				</div>

			</div>
		</main>

  		<footer>
        	<div class="foot">
        		<div class="left-column">

          			<div class="social_media">
			            <a href="L" target="_blank"><i class="fab fa-facebook-f"></i></a>
			            <a href="" target="_blank"><i class="fab fa-twitter"></i></a>
			            <a href="" target="_blank"><i class="fab fa-instagram"></i></a>
			            <a href="" target="_blank"><i class="fab fa-youtube"></i></a>
			            <a href="" target="_blank"><i class="fab fa-vk"></i></a>
          			</div>

          			<p class="foot_text">© 2021 Created By <a href="" id="me">JDK team</a> All Rights Reserved.</p>
       	 		</div>

       			 <div class="right-column">
						<h1 class="h1-r-col">Our Newsletter</h1>
          				<div class="border"></div>
         				<p class="border-text">Enter Your Email to get our news and updates.</p>
          			<form action="" class="newsletter-form">
            			<input type="text" class="mailing" placeholder="Enter Your Email">
           				<input type="submit" class="submit_button" value="submit">
           			</form>
           		</div>
           	</div>
        </footer>
        <!--<script type="text/javascript""></script>-->
		<script>
			var video = document.querySelector(".video");
			var juice = document.querySelector(".orange-juice");
			var button = document.getElementById("play-pause");

			function togglePlayPause(){
				if(video.paused){
					button.className = "pause";
					video.play();
				}
				else{
					button.className = "play";
					video.pause();
				}
			};

			button.onclick = function() {
				togglePlayPause();
			};

			video.addEventListener("timeupdate", function(){
				var juicePos = video.currentTime/video.duration;
				juice.style.width = juicePos * 100 + "%";
				if (video.ended){
					button.className = "play";
				}
			})

			window.onload = function(){
				document.querySelector('.tabs-header').addEventListener('click', fTabs);

				function fTabs(event){
					console.log(event);
					if(event.target.className == 'tab-h'){
						var dataTab = event.target.getAttribute('data-tab');

						var tabH = document.getElementsByClassName('tab-h');
						for( var i = 0; i<tabH.length; i++){
							tabH[i].classList.remove('active-border');
						}
						event.target.classList.add('active-border');
						var tabBody = document.getElementsByClassName('tab-b');
						for( var i = 0; i<tabBody.length; i++){
							if(dataTab == i)
							{
								tabBody[i].style.display = 'block';
							}
							else {
								tabBody[i].style.display = 'none';
							}
						}
					}
				}
			}
		</script>
</body>
</html>

templates/admin_panel.html
{%extends "layout.html" %}

{%block title%}
About
{%endblock%}

{%block content%}

<div class="shadowed p-5 mb-5 mt-2">
    <div class="row text-center">
        <div class="col">
            <h1 class="admin-title"><b>Admin panel</b></h1>
        </div>
    </div>
    <div class="row mt-5 text-center">
        <div class="col-3 admin-text">
            <a href="http://127.0.0.1:8000/user_all/">All Users</a><br>
        </div>
        <div class="col-3 admin-text">
            <a href="http://127.0.0.1:8000/create_user/">Create User</a><br>
        </div>
            {#    <a href="http://127.0.0.1:8000/update_user/">Update User</a><br>#}
    <div class="col-3 admin-text">
        <a href="http://127.0.0.1:8000/course_all/">All Courses</a><br>
    </div>
    <div class="col-3 admin-text">
        <a href="http://127.0.0.1:8000/create_course/">Create Course</a><br>
    </div>
        {#<a href="http://127.0.0.1:8000/update_course/">Update Course</a><br>#}
    </div>
</div>

{%endblock%}

templates/all_users.html
{% extends "layout.html" %}
{% block content %}
    <div class = "shadowed mt-2 mb-5 p-5 all-users">
        <h1 class="text-center">List</h1>
    {% for user in all %}
        <h2>{{ user.username }}</h2>
    {% endfor %}
    </div>
{% endblock %}

templates/cpp.html
{%extends "layout.html" %}

{%block title%}
Team
{%endblock%}

{%block content%}

<div class="shadowed mt-2 mb-5 p-5 text-center">
    <h2 class="course-title"><a href="cpp_lesson1">Lesson 1</a></h2>
    <h2 class="course-title"><a href="cpp_lesson2">Lesson 2</a></h2>
</div>
{%endblock%}

templates/cpp_lesson1.html
{%extends "layout.html" %}

{%block title%}
Team
{%endblock%}

{%block content%}

<div class="shadowed mt-2 mb-5 p-5">
    <div class="text-center">
        <iframe width="950" height="500" src="https://www.youtube.com/embed/9F3wgbaoTxs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
   <div class="homework-text mt-5">
    <h1>Homework:</h1>
    <h3>Print Hello World in console</h3>
    <br>
    <h4>Put your solution here</h4>
    </div>
<form method = 'POST' enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {% for field in create %}
            <tr>
                <th style="color:white;font-family: 'Open Sans'">{{field.label}}</th>
                <td style="height: 60px; width: 100px;">{{ field }}</td>
            </tr>
            {% endfor %}
        </table>
        <button type="submit" class="btn btn-lg btn-warning">Submit</button>
    </form>
</div>
{%endblock%}

templates/create_user.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="display-3" style="background-color:#000000;color:#FFFF99;">Create</h1>
    <form method = 'POST' enctype="multipart/form-data">
        {% csrf_token %}
        <table class = 'w-50 table table-light' style="border-radius:10px;background-color:#FFFF99;">
            {% for field in create %}
            <tr>
                <th>{{field.label}}</th>
                <td>{{ field }}</td>
            </tr>
            {% endfor %}
        </table>
        <button type="submit" class="btn btn-lg btn-warning">Submit</button>
    </form>
{% endblock %}

templates/index.html
{%extends "layout.html" %}

{%block title%}
EduPro - free Python courses
{%endblock%}

{%block content%}
	<div class="index_page shadowed">
		<div class="greeting">
			<h1>Click. Create. Enjoy.</h1>
		</div>
		<div class="columns">
            {% if courses %}
            {% for course in courses %}
                <div class="course">course</div>
            {% endfor %}
            {% else %}
			    <p>Here you can find courses to learn Python programming language!</p>
            {% endif %}
		</div>

	</div>
{%endblock%}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>
          {%block title%}

          {%endblock%}
        </title>
        {% load static %}
         <link rel="stylesheet"  href="{%  static  'css/main.css'  %}">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" charset="utf-8"></script>
	    <script src="https://kit.fontawesome.com/80480a3d8b.js" crossorigin="anonymous"></script>

	</head>
	<body>
		<header>
			<a href="{% url 'student:index' %}"><img src="img\headlogo.png" alt="" class="logoh"></a>

	        <!--Navigation bar-->
	        <nav>
	        	<ul class="navigation">
		         	<li><a href="{% url 'student:index' %}"><i class="fas fa-home home"></i> Home</a></li>
		       	 	<li><a href="{% url 'student:about' %}"><i class="fas fa-align-left about"></i> About</a></li>
		            <li><a href="{% url 'student:team' %}"><i class="fas fa-users team"></i> Team</a></li>
		            {%block login%}
                {% if user.is_authenticated%}
                    <li><a href="{% url 'logout' %}"><i class="fas fa-sign-in-alt login"></i> Logout </a></li>
                    <li><a href="{% url 'student:profile' user.username%}">{{user.username}}</a></li>

                {%else%}
                	<li><a href="{% url 'login' %}"><i class="fas fa-sign-in-alt login"></i> Login</a></li>
					<li><a href="{% url 'student:registration' %}"><i class="fas fa-sign-in-alt login"></i> Registration</a></li>
                {%endif%}
                {%endblock%}
	            </ul>
	        </nav>
 			<!--Logo of the menu which will show up when the screen is reduced-->
	        <i class="menu fas fa-bars"></i>
	        <div class="progress-container">
    			<div class="progress-bar" id="myBar"></div>
  			</div>
		</header>

        <main>
          {% block content %}
          {% endblock %}
        </main>

  		<footer>
        	<div class="foot">
        		<div class="left-column">
          			<img src="" alt="" class="logof">

          			<div class="social_media">
			            <a href="" target="_blank"><i class="fab fa-facebook-f"></i></a>
			            <a href="" target="_blank"><i class="fab fa-twitter"></i></a>
			            <a href="" target="_blank"><i class="fab fa-instagram"></i></a>
			            <a href="" target="_blank"><i class="fab fa-youtube"></i></a>
			            <a href="" target="_blank"><i class="fab fa-vk"></i></a>
          			</div>

          			<p class="foot_text">© 2021 Created By <a href="https://github.com/basotyev/education_system" id="me">JDK team</a> All Rights Reserved.</p>
       	 		</div>

       			 <div class="right-column">
						<h1 class="h1-r-col">Our Newsletter</h1>
          				<div class="border"></div>
         				<p class="border-text">Enter Your Email to get our news and updates.</p>
          			<form method="post" action="" class="newsletter-form">
            			<input type="text" class="mailing" placeholder="Enter Your Email">
           				<input type="submit" class="submit_button" value="submit">
           			</form>
           		</div>
           	</div>
        </footer>
		<script type="text/javascript" src="{% static 'js/java.js'%}"></script>
	</body>
</html>

templates/python.html
{%extends "layout.html" %}

{%block title%}
Team
{%endblock%}

{%block content%}

<div class="shadowed mt-2 mb-5 p-5 text-center">
    <h2 class="course-title"><a href="python_lesson1">Lesson 1</a></h2>
    <h2 class="course-title"><a href="python_lesson2">Lesson 2</a></h2>
</div>
{%endblock%}

templates/python_lesson1.html
{%extends "layout.html" %}

{%block title%}
Team
{%endblock%}

{%block content%}

<div class="shadowed mt-2 mb-5 p-5">
    <div class="text-center">
    <iframe width="950" height="500" src="https://www.youtube.com/embed/k9TUPpGqYTo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <div class="homework-text mt-5">
    <h1>Homework:</h1>
    <h3>Print Hello World in console</h3>
    <br>
    <h4>Put your solution here</h4>
    </div>
<form method = 'POST' enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {% for field in create %}
            <tr>
                <th style="color:white;font-family: 'Open Sans'">{{field.label}}</th>
                <td style="height: 60px; width: 100px;">{{ field }}</td>
            </tr>
            {% endfor %}
        </table>
        <button type="submit" class="btn btn-lg btn-warning">Submit</button>
    </form>
</div>
{%endblock%}

templates/python_lesson2.html
{%extends "layout.html" %}

{%block title%}
Team
{%endblock%}

{%block content%}

<div class="shadowed mt-2 mb-5 p-5">
    <div class="text-center">
        <iframe width="950" height="500" src="https://www.youtube.com/embed/khKv-8q7YmY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
<div class="homework-text mt-5">
    <h1>Homework:</h1>
    <h3>Do examples on all arithmetic operations</h3>
    <br>
    <h4>Put your solution here</h4>
    </div>
<form method = 'POST' enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {% for field in create %}
            <tr>
                <th style="color:white;font-family: 'Open Sans'">{{field.label}}</th>
                <td style="height: 60px; width: 100px;">{{ field }}</td>
            </tr>
            {% endfor %}
        </table>
        <button type="submit" class="btn btn-lg btn-warning">Submit</button>
    </form>
</div>
{%endblock%}

templates/teacher.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>
          {%block title%}

          {%endblock%}
        </title>
        {% load static %}
         <link rel="stylesheet"  href="{%  static  'css/main.css'  %}">
        <link rel="stylesheet"  href="{%  static  'css/bootstrap.min.css'  %}">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" charset="utf-8"></script>
	    <script src="https://kit.fontawesome.com/80480a3d8b.js" crossorigin="anonymous"></script>

	</head>
	<body>
		<header>
			<a href="{% url 'student:index' %}"><img src="img\headlogo.png" alt="" class="logoh"></a>

	        <!--Navigation bar-->
	        <nav>
	        	<ul class="navigation">
		         	<li><a href="{% url 'student:index' %}"><i class="fas fa-home home"></i> Home</a></li>
		       	 	<li><a href="{% url 'student:about' %}"><i class="fas fa-align-left about"></i> About</a></li>
		            <li><a href="{% url 'student:team' %}"><i class="fas fa-users team"></i> Team</a></li>
		            {%block login%}
                {% if user.is_authenticated%}
                    <li><a href="{% url 'logout' %}"><i class="fas fa-sign-in-alt login"></i> Logout </a></li>
                    <li><a href="{% url 'student:profile' user.username%}">{{user.username}}</a></li>
                    <label for="hw"><a style="color: white">Notifications: {{ user.notifications.unread.count }}</a></label>
                    <select name="Notifications ">
  {% for notification in  user.notifications.unread %}
          <option>New Homework from <b>{{ notification.actor }} </b></option>
	{% endfor %}
</select>

                {%else%}
                	<li><a href="{% url 'login' %}"><i class="fas fa-sign-in-alt login"></i> Login</a></li>
					<li><a href="{% url 'student:registration' %}"><i class="fas fa-sign-in-alt login"></i> Registration</a></li>
                {%endif%}
                {%endblock%}
	            </ul>
	        </nav>
 			<!--Logo of the menu which will show up when the screen is reduced-->
	        <i class="menu fas fa-bars"></i>
	        <div class="progress-container">
    			<div class="progress-bar" id="myBar"></div>
  			</div>
		</header>

        <main>
<div class="shadowed p-5 mt-2 mb-5">
    <div class="row justify-content-center">
{% block content %}
        <h1 class="text-center mb-3" style="color:white;">Homeworks</h1>
        {% for hw in all %}
            <div class="col teacher-text">
                <h4>Username: {{ hw.username }}</h4>
                <h4>Lesson: {{ hw.lesson }}</h4>
                <h4>Solution: {{ hw.solution }}</h4>
            </div>
        {% endfor %}

{% endblock %}
    </div>
    </div>
        </main>

  		<footer>
        	<div class="foot">
        		<div class="left-column">
          			<img src="" alt="" class="logof">

          			<div class="social_media">
			            <a href="" target="_blank"><i class="fab fa-facebook-f"></i></a>
			            <a href="" target="_blank"><i class="fab fa-twitter"></i></a>
			            <a href="" target="_blank"><i class="fab fa-instagram"></i></a>
			            <a href="" target="_blank"><i class="fab fa-youtube"></i></a>
			            <a href="" target="_blank"><i class="fab fa-vk"></i></a>
          			</div>

          			<p class="foot_text">© 2021 Created By <a href="https://github.com/basotyev/education_system" id="me">JDK team</a> All Rights Reserved.</p>
       	 		</div>

       			 <div class="right-column">
						<h1 class="h1-r-col">Our Newsletter</h1>
          				<div class="border"></div>
         				<p class="border-text">Enter Your Email to get our news and updates.</p>
          			<form method="post" action="" class="newsletter-form">
            			<input type="text" class="mailing" placeholder="Enter Your Email">
           				<input type="submit" class="submit_button" value="submit">
           			</form>
           		</div>
           	</div>
        </footer>
		<script type="text/javascript" src="{% static 'js/java.js'%}"></script>
	</body>
</html>

templates/team.html
{%extends "layout.html" %}

{%block title%}
Team
{%endblock%}

{%block content%}

<div class="shadowed p-3 mt-2 mb-5">
    <div class="container-fluid">
        <div class="row justify-content-center m-5">
            <div class="col-2">
            <img class="float-end" src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1024px-Python-logo-notext.svg.png"
    width="100" height="100">
            </div>
            <div class="col-3 align-self-center">
                <h2 class="course-title"><a href="python">Python Lessons</a></h2>
            </div>
        </div>
        <div class="row justify-content-center m-5">
            <div class="col-2">
                <img class="float-end" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/1822px-ISO_C%2B%2B_Logo.svg.png" width="100" height="100">
            </div>
            <div class="col-3 align-self-center">
                <h2 class="course-title"><a href="cpp">C++ Lessons</a></h2>
            </div>
        </div>
    </div>
</div>
{%endblock%}

templates/update_user.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="display-3" style="background-color:#000000;color:#FFFF99;">Update User</h1>
    <form method = 'POST' enctype="multipart/form-data">
        {% csrf_token %}
        <table class = 'w-50 table table-light' style="border-radius:10px;background-color:#FFFF99;">
            {% for field in update %}
            <tr>
                <th>{{field.label}}</th>
                <td>{{ field }}</td>
            </tr>
            {% endfor %}
        </table>
        <button type="submit" class="btn btn-lg btn-warning">Submit</button>
    </form>
{% endblock %}